# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 15:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('insumo', '0001_initial'),
        ('obra', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='presupuesto',
            fields=[
                ('idPresupuesto', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precoParcial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('codigo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='insumo.insumo')),
                ('nit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='obra.obra')),
            ],
        ),
    ]
