# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='obra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.CharField(max_length=10)),
                ('nombreO', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('observacioneso', models.CharField(max_length=200)),
            ],
        ),
    ]
