# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='insumo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('nombreI', models.CharField(max_length=100)),
                ('detalle', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('unidad', models.CharField(max_length=50)),
                ('observaciones', models.CharField(max_length=200)),
            ],
        ),
    ]
